set -g status-left-length 200   # default: 10
set -g status-right-length 200  # default: 10
set -g status-justify centre

# Theme
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=${black},bold,bg=blue]  #S #[bg=default]"
set -g status-right " #{cpu_percentage} |  #{ram_percentage} | #[fg=blue]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg=brightblack] #I:#W "
set -g window-status-current-format "#[fg=blue,bold] #I:#W "
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=blue"
set -g message-style "bg=default,fg=blue"
set -g message-command-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
setw -g clock-mode-colour blue
